#docker compose -f ./Containers/MenuStore/docker-compose.yml up
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./MenuStoreData.json:/MenuStoreData.json
      - ./MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    ports:
      - 27017:27017
