#docker compose -f ./Containers/MenuStore/docker-compose.yml up
services:
  mongo:
    image: mongo:latest
    container_name: MenuStore
    restart: always
    volumes:
      - ./MenuStoreData.json:/MenuStoreData.json
      - ./MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    