
services: 
 # python_request:
  #  container_name: kitchenview
  #build: ./BurgerOrderer
  # # depends_on:
    #   website:
    #     condition: service_started
#ports:
  #  - 8081:8081
  # restart: always

  kitchenview:
    container_name: kitchenview
    build: ./KitchenView

    ports:
      - "3001:3001"
    restart: always

  website:
    container_name: burgerorder
    build: ./BurgerOrderer
    ports: 
      - "3000:3000"
     #depends_on:
      # - database
     #environment:
    #   DB_Host: database 
    #   DB_USER: root
    #   DB_PASSWORD: ""
    #   DB_NAME: ""
    restart: always
  
  # database: 
  #   image:  mongo
  #   container_name: MenuStore
  #   ports:
  #     - "27017:27017"
  #   restart: always
  #   volumes:
  #     - ./MenuStoreData.json:/MenuStoreData.json
  #     - ./MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    
    
