
services: 
  python_request:
    container_name: kitchen_view
    build: ./KitchenView
    # depends_on:
    #   website:
    #     condition: service_started
    restart: always

  website:
    container_name: burgerorder
    build: ./BurgerOrderer
    ports: 
      - "8080:8080"
    # depends_on:
    #   - database
    # environment:
    #   DB_Host: database 
    #   DB_USER: root
    #   DB_PASSWORD: ""
    #   DB_NAME: ""
    restart: always
  
  # database: 
  #   image:  mongo
  #   container_name: MenuStore
  #   ports:
  #     - "27017:27017"
  #   restart: always
  #   volumes:
  #     - ./MenuStoreData.json:/MenuStoreData.json
  #     - ./MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    
    
