version: "3"
services: 
  python:
    container_name: kitchen_view
    image: python 3.9
      

  website:
    image: burgerorder
    ports: 
      -"8080:8081"
    restart: always
  
  database: 
    mongo:
      image: mongo:latest
      container_name: MenuStore
      restart: always
      volumes:
        - ./MenuStoreData.json:/MenuStoreData.json
        - ./MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    
    
