version: "3"
services: 
  pythonRequest:
    container_name: kitchen_view
    build: ./kitchen_view
    depends_on:
      website:
        condition: service_started
    restart: always

  website:
    image: burgerorder
    ports: 
      -"8080:8081"
    depends_on:
      - database:
    # environment:
    #   DB_Host: database 
    #   DB_USER: root
    #   DB_PASSWORD: ""
    #   DB_NAME: ""
    restart: always
  
  database: 
    mongo:
      image: mongo:latest
      container_name: MenuStore
      restart: always
      volumes:
        - ./MenuStoreData.json:/MenuStoreData.json
        - ./MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    
    
