
services: 
  # python_request:
    #  container_name: kitchenview
    #build: ./BurgerOrderer
    # # depends_on:
      #   website:
      #     condition: service_started
  #ports:
    #  - 8081:8081
    # restart: always

  kitchenview:
    container_name: kitchenview
    build: ./KitchenView
    volumes:
       - ./KitchenView:/app
        - /app/node_modules #Creates a node_modles volume because program could not find package.json otherwise
    depends_on:
      website:
        condition: service_started
    ports:
      - "3001:3001"
   
    restart: always

  website:
    container_name: burgerorder
    build: ./BurgerOrderer
    volumes:
        - ./BurgerOrderer:/app
        - /app/node_modules
    depends_on:
      - mongodb
   
    ports: 
      - "3000:3000"
    
    
    #environment:
    #   DB_Host: database 
    #   DB_USER: root
    #   DB_PASSWORD: ""
    #   DB_NAME: ""
    restart: always
  
  mongodb:
    image: mongo:latest
    container_name: menustore
    restart: always
    
    volumes:
        - ./MenuStore/data/MenuStoreData.json:/data/db/MenuStoreData.json
        - ./MenuStore/data/MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    ports:
      - 27017:27017
# volumes:
#   - .MenuStore/data/MenuStoreData.json
#   - .MenuStore/data/MakeDatabase.sh:/docker

    
