
services: 
  python_request:
    container_name: kitchenview
    build: ./KitchenView
    depends_on:
      website:
        condition: service_started
    ports:
     - 8081:8081
    restart: always

  website:
    container_name: burgerorder
    build: ./BurgerOrderer
    ports: 
      - "8080:8080"
    depends_on:
      - mongodb
    # environment:
    #   DB_Host: database 
    #   DB_USER: root
    #   DB_PASSWORD: ""
    #   DB_NAME: ""
    restart: always
  
  mongodb:
    image: mongo:latest
    
    restart: always
    command: tail -f /dev/null
    volumes:
      - .MenuStore/data/MenuStoreData.json:/data/db/MenuStoreData.json
      - .MenuStore/data/MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    ports:
      - 27017:27017

    
