#docker compose -f ./Containers/MenuStore/docker-compose.yml up
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/MenuStoreData.json:/data/db/MenuStoreData.json
      - ./data/MakeDatabase.sh:/docker-entrypoint-initdb.d/MakeDatabase.sh
    ports:
      - 27017:27017
