FROM ubuntu:latest

RUN apt update
RUN apt install python3 -y
RUN apt install 
RUN apt-get install python3-requests
WORKDIR /KitchenView

COPY . /kitchenView.py

CMD [ "python3", "./kitchenView.py" ]



